sub ture

/call InternalMoveTo 2962.25 585.00

/call InternalMoveTo 2866.32 588.53
/call KillFace 60
/if (!${SpawnCount[NPC radius 40]} == 0) {
/call coh
} else {
/call KillFace 60
/call coh
}

/call InternalMoveTo 3148.72 589.67

/call InternalMoveTo 2963.46 585.11
/call KillFace 60
/if (!${SpawnCount[NPC radius 40]} == 0) {
/call coh
} else {
/call KillFace 60
/call coh
}

/call InternalMoveTo 2962.25 585.00

/return