sub t2

/call zonecheck

/call RanInternalMoveTo 1592.74 686.98

/call killit

/call RanInternalMoveTo 1353.98 802.31





/call RanInternalMoveTo 1255.47 932.95




/call RanInternalMoveTo 1220.51 991.26


/call RanInternalMoveTo 1253.67 1112.89

/call RanInternalMoveTo 1295.55 1162.65

/call killit



/call RanInternalMoveTo 1283.68 1210.53

/call killit
/call zonecheck

/call RanInternalMoveTo 1224.47 1346.78
/delay 1s

/call RanInternalMoveTo 1250.25 1303.75




/call RanInternalMoveTo 1147.42 1468.68

/call RanInternalMoveTo 1021.77 1563.82


/call RanInternalMoveTo 1199.02 1640.25





/call RanInternalMoveTo 1431.64 1671.33

/call killit
/call zonecheck

/call RanInternalMoveTo 1646.65 1926.09


/call RanInternalMoveTo 1693.18.64 2142.87





/call RanInternalMoveTo 1479.35 2119.13


/call RanInternalMoveTo 1501.68 2218.58


/call RanInternalMoveTo 1377.49 2130.06


/call RanInternalMoveTo 1267.75 1932.77



/call RanInternalMoveTo 1213.09 2114.66


/call RanInternalMoveTo 1057.99 2042.67
/call killit
/call zonecheck

/call RanInternalMoveTo 931.62 1763.52


/call RanInternalMoveTo 796.49 1642.25


/call RanInternalMoveTo 736.30 1480.19

/call RanInternalMoveTo 698.41 1459.21



/call RanInternalMoveTo 946.11 1223.91
/call killit
/call zonecheck





/call RanInternalMoveTo 794.96 950.49




/call RanInternalMoveTo 675.43 1042.68


/loc


/call RanInternalMoveTo 437.69 1023.30


/loc



/call RanInternalMoveTo 427.95 857.69

/loc

/call RanInternalMoveTo 399.30 758.12

/loc

/call RanInternalMoveTo 341.81 698.71


/loc

/call RanInternalMoveTo 93.98 556.35
/call killit
/call zonecheck

/loc
/call RanInternalMoveTo 64.56 532.67


/loc
/call RanInternalMoveTo -240.04 604.70


/call RanInternalMoveTo -347.13 746.60

/loc


/call RanInternalMoveTo -539.43 809.45


/call RanInternalMoveTo -615.02 924.12
/call killit
/call LootIt 100



/call RanInternalMoveTo -790.78 803.52
/loc


/call RanInternalMoveTo -815.34 751.36
/call killit
/call LootIt 100




/call RanInternalMoveTo -818.44 633.95

/call RanInternalMoveTo -816.18 719.43

/call RanInternalMoveTo -852.83  508.14

/call RanInternalMoveTo -697.20 517.32
/call killit

/loc



/call RanInternalMoveTo -566.75 281.48


/call RanInternalMoveTo -655.04 168.25
/call RanInternalMoveTo -498.04 -234.84
/call RanInternalMoveTo -254.56 -651.17
/call RanInternalMoveTo -462.48 -157.37
/call killit
/call zonecheck

/loc



/call RanInternalMoveTo -133.84 -788.49

/call RanInternalMoveTo -72.75 -794.59


/face heading 279

/loc




/call RanInternalMoveTo -54.91 -888.19
/call killit
/call LootIt 100

/loc




/call RanInternalMoveTo -107.45 -961.35


/loc




/call RanInternalMoveTo -166.08 -990.86

/loc



/call RanInternalMoveTo -255.54 -1003.49




/call RanInternalMoveTo -300.35 -928.35


/loc



/call RanInternalMoveTo -631.41 -770.59


/loc



/call RanInternalMoveTo -686.66 -658.63


/loc



/call RanInternalMoveTo -775.96 -847.28


/loc



/call RanInternalMoveTo -1479.90 -972.16
/call killit
/call LootIt 100


InternalMoveTo -1479.90 -972.16
/loc



/call RanInternalMoveTo -1622.27 -802.22

/loc



/call RanInternalMoveTo -1792.09 -696.31

/loc



/call RanInternalMoveTo -2019.51 -823.49
/call killit

/loc



/call RanInternalMoveTo -1922.85 -1305.15

/loc








/delay 1s

/if (${SpawnCount[npc radius 60]} > 1) {
  /target npc radius 60
  /stick 1 uw
  /attack on
/call killit
}

/return

sub pod2

/call RanInternalMoveTo -2141.84 -1095.46




/call RanInternalMoveTo -2076.62 -880.54




/call RanInternalMoveTo -2185.05 -806.12


/call RanInternalMoveTo -2225.74 -621.32

/call RanInternalMoveTo -1873.90 -732.15
/call killit
/call LootIt 100

/call RanInternalMoveTo -1730.22 -1040.28




/call RanInternalMoveTo -1676.05 -1256.68
/call killit
/call LootIt 100

/call RanInternalMoveTo -1753.86 -1058.66
/call killit
/call LootIt 100

/call RanInternalMoveTo -1669.43 -738.39
/call killit
/call LootIt 100

/call RanInternalMoveTo -1481.84 -546.53
/call killit
/call LootIt 100

/call RanInternalMoveTo -1117.66 -614.32
/call killit
/call LootIt 100




/call RanInternalMoveTo -1137.07 -1183.61



/call RanInternalMoveTo -1234.08 -1052.78



/call RanInternalMoveTo -1346.68 -1024.56



/call RanInternalMoveTo -1363.93 -743.37



/call RanInternalMoveTo -1447.84 -621.03


/call RanInternalMoveTo -1542.65 -446.85
/call killit



/call RanInternalMoveTo -1694.36 -252.41


/call RanInternalMoveTo -1814.29 -345.77


/call RanInternalMoveTo -1739.47 -96.20




/call RanInternalMoveTo -1967.28 -56.33


/call RanInternalMoveTo -1952.38 112.46
/call killit

/call RanInternalMoveTo -1987.67 35.38




/call RanInternalMoveTo -2079.99 -2.86


/call RanInternalMoveTo -2186.16 -170.62


/call RanInternalMoveTo -2179.65 102.01




/call RanInternalMoveTo -2079.99 -2.86
/call killit

/call RanInternalMoveTo -2186.16 -170.62


/call RanInternalMoveTo -2179.65 102.01




/call RanInternalMoveTo -1993.34 406.26


/call RanInternalMoveTo -2121.96 540.95


/call RanInternalMoveTo -2172.94 670.20
/call killit



/call RanInternalMoveTo -2159.84 930.63

/call RanInternalMoveTo -1540.16 926.92



/call RanInternalMoveTo -1815.01 970.70


/call RanInternalMoveTo -1892.30 1107.17

/call RanInternalMoveTo -1844.84 1361.92
/call killit

/call RanInternalMoveTo -2105.83 1434.12




/call RanInternalMoveTo -1740.88 1266.94

/call RanInternalMoveTo -1525.97 969.64

/call RanInternalMoveTo -1492.27 628.05




/call RanInternalMoveTo -1287.06 650.80
/call killit

/call RanInternalMoveTo -1192.25 635.04


/call RanInternalMoveTo -1140.88 672.38


/call RanInternalMoveTo -1088.15 825.82




/call RanInternalMoveTo -1196.30 1054.52


/call RanInternalMoveTo -1140.32 1217.18
/call killit

/call RanInternalMoveTo -1023.69 1322.85
/call killit


/return

sub pod3

/call RanInternalMoveTo -764.74 1473.13
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -969.64 1758.25
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1202.73 1838.79
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100




/call RanInternalMoveTo -1275.96 2101.31
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1539.18 2050.61
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1376.98 1724.37
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100




/call RanInternalMoveTo -1192.25 635.04
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1141.06 1524.12
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1123.85 1623.20
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100




/call RanInternalMoveTo -1174.34 1782.61
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1092.20 2064.76
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -856.35 1937.64
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100



/call RanInternalMoveTo -934.93 2121.54
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100



/call RanInternalMoveTo -1092.20 2064.76
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -856.35 1937.64
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100




/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1092.20 2064.76
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -856.35 1937.64
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100




/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -1092.20 2064.76
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call RanInternalMoveTo -856.35 1937.64
/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100






/return

sub zonecheck 



/if (!${Zone.Name.Equal[Plane of Dragons]}) {
/camp
/delay 40s
/endmacro
}  else {

/return

}


sub killit

/call getitem 8 8

/call KillAllMobs 10 60
/delay 1s
/call KillAllMobs 10 60
/call LootIt 100

/call storeweapon 8 8

/return
