sub f7

/call RanInternalMoveTo 267.20,20.61
/call RanInternalMoveTo 315.17,20.00
/call RanInternalMoveTo 351.19,22.00
/call RanInternalMoveTo 398.97,43.73
/call RanInternalMoveTo 399.21,62.70
/call RanInternalMoveTo 451.96,62.55
/call RanInternalMoveTo 454.00,-17.12
/call RanInternalMoveTo 402.64,-20.57
/call RanInternalMoveTo 397.46,19.89
/call RanInternalMoveTo 246.47,20.57

/return