sub fs3
| need to add CoH code based on if group

/call InternalMoveTo 770.11 668.52
/call InternalMoveTo 779.02 630.96
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 849.61 629.08
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 779.13 631.42
/call InternalMoveTo 774.26 598.60
/call InternalMoveTo 780.69 467.55
/call InternalMoveTo 779.69 491.74
/call KillAllMobs 10 20
/call LootIt 40
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 808.95 443.68
/call InternalMoveTo 804.93 443.56
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 891.68 438.23
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 861.19 469.10
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 896.13 547.68
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 910.85 566.54
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1022.08 565.44
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1027.06 506.83
/call KillAllMobs 10 20
/call LootIt 40
/call buffup
/call InternalMoveTo 983.75 420.27
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1019.13 434.39
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1056.32 446.18
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1062.56 430.51
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1129.64 432.98
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1153.54 499.80
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1030.39 511.16
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 1028.18 571.00
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 874.86 567.23
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 873.81 546.75
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 775.06 547.44
/call KillAllMobs 10 20
/call LootIt 40
/call InternalMoveTo 774.86 669.30
/call KillAllMobs 10 20
/call LootIt 40
/call KillAllMobs 10 20



/return