/call RanInternalMoveTo /call RanInternalMoveTo 455.27 93.92
/call RanInternalMoveTo /call RanInternalMoveTo 536.32 93.55
/call RanInternalMoveTo /call RanInternalMoveTo 564.62 27.53
/call RanInternalMoveTo /call RanInternalMoveTo 547.09 53.11
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 558.60 6.86
/call RanInternalMoveTo /call RanInternalMoveTo 623.45 6.06
/call RanInternalMoveTo /call RanInternalMoveTo 618.57 -22.03
/call RanInternalMoveTo 
/call RanInternalMoveTo /call RanInternalMoveTo 609.84 -19.22
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 621.32 -5.59
/call RanInternalMoveTo /call RanInternalMoveTo 622.25 9.69
/call RanInternalMoveTo /call RanInternalMoveTo 664.68 7.71
/call RanInternalMoveTo /call RanInternalMoveTo 662.85 28.86
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 664.68 7.71
/call RanInternalMoveTo /call RanInternalMoveTo 719.23 6.56
/call RanInternalMoveTo /call RanInternalMoveTo 720.92 29.59
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 719.23 6.56
/call RanInternalMoveTo /call RanInternalMoveTo 572.41 7.85
/call RanInternalMoveTo /call RanInternalMoveTo 518.43 -54.15
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 483.17 -25.35
/call RanInternalMoveTo /call RanInternalMoveTo 535.87 -1.96
/call RanInternalMoveTo /call RanInternalMoveTo 536.51 15.57
/call RanInternalMoveTo /call RanInternalMoveTo 520.17 19.66
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 511.76 8.89
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo /call RanInternalMoveTo 518.73 -1.84
/call RanInternalMoveTo /call RanInternalMoveTo 529.31 -3.81
/call RanInternalMoveTo /call RanInternalMoveTo 537.85 8.65
/call RanInternalMoveTo /call RanInternalMoveTo 540.95 92.98
/call RanInternalMoveTo /call RanInternalMoveTo 456.99 95.04
/call RanInternalMoveTo FIGHT
/call RanInternalMoveTo 
