sub unrest
/call InternalMoveTo 719.29 -188.26
/call KillFace 60
/call InternalMoveTo 788.41 -136.77
/call KillFace 60
/call InternalMoveTo 68.38 -0.55
/call KillFace 60
/call InternalMoveTo 409.40 0.25
/call KillFace 60
/call InternalMoveTo 481.65 -187.06
/call KillFace 60
/call InternalMoveTo 506.91 -271.56
/call KillFace 60
/call InternalMoveTo 493.84 -154.79
/call KillFace 60
/call InternalMoveTo 801.45 40.12
/call KillFace 60
/call InternalMoveTo 742.98 224.65
/call KillFace 60
/call InternalMoveTo 574.55 146.69
/call KillFace 60
/call InternalMoveTo 456.41 106.05
/call KillFace 60
/call InternalMoveTo 415.75 10.70
/call KillFace 60
/call InternalMoveTo 502.51 0.84
/call KillFace 60
/call InternalMoveTo 502.08 35.89
/call KillFace 60
/call InternalMoveTo 610.54 40.15
/call KillFace 60
/call InternalMoveTo 611.89 -35.60
/call KillFace 60
/call InternalMoveTo 532.58 -42.50
/call KillFace 60
/call InternalMoveTo 506.88 -36.59
/call KillFace 60
/call InternalMoveTo 502.59 -1.83
/call KillFace 60
/call InternalMoveTo 124.95 -0.21
/call KillFace 60

/return