#Event Repop "You already repop this zone within last 10 minutes."

sub hate

|/goto :block5

|Divide into Heavens and Hate

:block1

/call InternalMoveTo -254.23 -2674.64
/call InternalMoveTo -2.75 -2674.36

/call InternalMoveTo -0.47 -2478.54

/call InternalMoveTo -0.76 -2101.75

/call InternalMoveTo 3.25 -2327.75

/call InternalMoveTo 394.96 -2321.54

/call InternalMoveTo 410.96 -2283.42

/call InternalMoveTo 385.05 -1926.50

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

:block2

/call InternalMoveTo 218.96 -1923.22

/call InternalMoveTo 382.35 -1920.33
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 400.35 -1721.21

/call InternalMoveTo 402.84 -1499.77

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call InternalMoveTo -11.55 -1537.31

/call InternalMoveTo -3.02 -1632.34
/call InternalMoveTo -7.85 -1543.42

/call InternalMoveTo -175.13 -1515.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo -390.18 -1515.65

/call InternalMoveTo -396.90 -1760.30
/call InternalMoveTo -390.87 -1915.19

/call InternalMoveTo -281.49 -1918.57




/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}


:block3

/call InternalMoveTo -377.27 -1918.38

/call InternalMoveTo -397.14 -2105.31
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo -389.74 -2325.82

/call InternalMoveTo 382.97 -2319.32

/call InternalMoveTo 387.62 -1972.55

/call InternalMoveTo 390.59 -1855.15

/call InternalMoveTo 395.08 -1180.99


/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call InternalMoveTo 397.98 -1062.72

/call InternalMoveTo 448.69 -1017.22

/call InternalMoveTo 803.45 -1016.54

/call InternalMoveTo 806.80 -1027.49
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 881.24 -1097.76

/call InternalMoveTo 876.76 -1412.53

/call InternalMoveTo 734.93 -1400.25

/call InternalMoveTo 729.58 -1450.34

/call InternalMoveTo 1024.39 -1450.56

/call InternalMoveTo 1041.09 -1407.96


:block4


/call InternalMoveTo 888.67 -1428.36

/call InternalMoveTo 881.34 -1925.46

/call InternalMoveTo 741.48 -1906.68
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 740.01 -1948.55

/call InternalMoveTo 1018.57 -1953.23

/call InternalMoveTo 1023.24 -1928.49

/call InternalMoveTo 879.81 -1924.83

/call InternalMoveTo 883.74 -2286.91

/call InternalMoveTo 993.56 -2322.13

/call InternalMoveTo 996.58 -2326.70

/call InternalMoveTo 1356.86 -2321.36

/call InternalMoveTo 1684.76 -2319.82

/call InternalMoveTo 1735.97 -2276.07

/call InternalMoveTo 1733.47 -2377.84

/call InternalMoveTo 1719.10 -2336.21
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

|Hate Ent|
/call InternalMoveTo 1702.38 -2320.35

/call InternalMoveTo 1875.99 -2321.20

/call InternalMoveTo 1886.48 -2518.12

/call InternalMoveTo 1942.45 -2429.83

/call InternalMoveTo 2074.62 -2424.94
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2103.58 -2546.22

/call InternalMoveTo 2109.40 -2345.00

/call InternalMoveTo 2200.59 -2317.81

/call InternalMoveTo 2116.90 -2247.43

/call InternalMoveTo 2102.88 -2114.08

/call InternalMoveTo 2032.69 -2208.85
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2152.21 -2320.77

:block5
/call InternalMoveTo 2626.10 -2330.54

/call InternalMoveTo 2565.33 -2530.80

/call InternalMoveTo 2669.33 -2364.64

/call InternalMoveTo 2720.74 -2472.46

/call InternalMoveTo 2800.92 -2362.06
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2890.19 -2534.97

/call InternalMoveTo 2886.05 -2107.65

/call InternalMoveTo 2722.10 -2377.71

/call InternalMoveTo 2725.00 -1783.72

/call InternalMoveTo 2721.43 -1759.09
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 2892.04 -1914.89

/call InternalMoveTo 2925.57 -1726.66

/call InternalMoveTo 2891.63 -1533.11

/call InternalMoveTo 2739.86 -1725.87

/call InternalMoveTo 2720.51 -1583.64

/call InternalMoveTo 2551.74 -1591.55

/call InternalMoveTo 2559.76 -1510.21
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2619.99 -1725.08

/call InternalMoveTo 2077.93 -1729.54

/call InternalMoveTo 2177.18 -1565.64

/call InternalMoveTo 2254.35 -1547.30

/call InternalMoveTo 2056.35 -1512.03

/call InternalMoveTo 1844.68 -1559.80
/call KillAllMobs 10 20
/delay 1s
/call KillAllMobs 10 20
/call LootIt 45
/call InternalMoveTo 2022.90 -1714.57

/call InternalMoveTo 1855.13 -1883.26

/call InternalMoveTo 2040.89 -1923.66

/call InternalMoveTo 2225.74 -1891.87
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 2040.89 -1923.66

/delay 3s
/call KillAllMobs 10 35
/delay 1s
/call KillAllMobs 10 35
/call LootIt 45

/return




sub xroad

/call InternalMoveTo -173.39 -2674.53


/call InternalMoveTo -6.42 -2664.50


/call InternalMoveTo -7.05 -2342.08

/call InternalMoveTo -360.79 -2317.46
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo -398.53 -2139.18


/call InternalMoveTo -396.12 -1141.09

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call InternalMoveTo -399.86 -1041.48


/call InternalMoveTo -217.89 -1017.65


/call InternalMoveTo -9.89 -1010.78

/call InternalMoveTo -1.63 -1010.54
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/call InternalMoveTo 7.03 -995.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/return


sub abyss


/call InternalMoveTo 10.19 -923.69

/call InternalMoveTo 1.61 -745.94

/call InternalMoveTo 5.42 -416.30

/call InternalMoveTo 4.29 -381.89

/call InternalMoveTo 2.54 -130.29
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -107.45 -254.26
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 126.43 -257.44

/call InternalMoveTo 588.96 -258.06

/call InternalMoveTo 717.75 -262.25

/call InternalMoveTo 733.16 -407.27

/call InternalMoveTo 701.23 -554.96

/call InternalMoveTo 812.96 -553.43

/call InternalMoveTo 758.80 -486.21

/call InternalMoveTo 735.54 -105.85
/call KillAllMobs 10 30
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 761.62 -43.58

/call InternalMoveTo 807.19 53.14

/call InternalMoveTo 736.41 61.64

/call InternalMoveTo 638.80 36.52

/call InternalMoveTo 713.03 -41.99
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 782.78 -253.17

/call InternalMoveTo 1345.04 -260.94

/call InternalMoveTo 1783.24 -257.05

/call InternalMoveTo 1858.47 -261.72
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/return

sub north

/call InternalMoveTo 2.20 -265.75

/call InternalMoveTo 736.02 -260.93

/call InternalMoveTo 1938.11 -259.02
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return


sub skies

/call InternalMoveTo 1964.83 -297.00

/call InternalMoveTo 1972.69 -529.38

/call InternalMoveTo 1972.17 -616.97

/call InternalMoveTo 1906.59 -730.64

/call InternalMoveTo 2019.44 -725.99
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1969.46 -747.37

/call InternalMoveTo 1969.88 -909.20

/call InternalMoveTo 1966.60 -1009.81

/call InternalMoveTo 1833.36 -1017.26

/call InternalMoveTo 1677.16 -1016.54

/call InternalMoveTo 1679.31 -1145.28

/call InternalMoveTo 1680.47 -1302.90
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1598.51 -1368.47

/call InternalMoveTo 1618.52 -1510.61
/call KillAllMobs 10 30

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1670.52 -1560.92

/call InternalMoveTo 1742.29 -1513.29

/call InternalMoveTo 1737.74 -1378.30

/call InternalMoveTo 1684.11 -1293.29

/call InternalMoveTo 1678.81 -1016.81

/call InternalMoveTo 2106.22 -1009.79

/call InternalMoveTo 2252.59 -1009.81

/call InternalMoveTo 2260.16 -1138.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2261.47 -1304.21

/call InternalMoveTo 2188.29 -1367.31

/call InternalMoveTo 2197.32 -1502.49


/call InternalMoveTo 2330.21 -1520.84

/call InternalMoveTo 2330.26 -1387.39
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/return

sub south

/call InternalMoveTo -496.21 -1020.17

/call InternalMoveTo -638.31 -1015.86

/call InternalMoveTo -998.10 -1020.88

/call InternalMoveTo -1127.03 -1058.92
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1130.56 -1356.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45



/return

sub uw

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call InternalMoveTo 1968.77 -115.69
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1969.71 261.67
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2030.05 296.16
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1914.69 292.43
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.65 281.38
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.74 437.64
/call KillAllMobs 10 30
/delay 1s
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2178.08 460.91
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1790.52 457.58
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1866.82 530.40
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1823.35 676.97
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1758.77 683.34
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2179.43 691.50
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2079.34 624.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.99 751.80
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1969.59 1036.95
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2159.81 1133.62
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1767.18 1131.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1985.80 1252.29
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2117.78 1296.58
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1981.52 1498.46
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2164.77 1460.64
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1766.95 1455.96
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1954.57 1293.13
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1633.30 1296.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1387.08 1297.03
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1571.92 1447.60
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1395.16 1502.06
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1163.21 1457.54
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1185.99 1461.06
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1369.69 1322.57
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1240.32 1293.14
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1249.11 1296.05
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1294.30 1151.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1184.53 1128.99
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1583.11 1132.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1374.19 1134.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1374.17 645.77
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1525.69 800.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1570.46 623.78
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1530.41 418.48
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1414.16 614.88
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1376.59 481.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1182.99 619.12
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1203.80 801.29
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1212.10 441.26
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return

sub storms

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call InternalMoveTo -1368.18 -1362.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1457.96 -1362.26
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1581.69 -1358.39
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1598.42 -1224.01
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1596.56 -1070.87

/call InternalMoveTo -1736.84 -1068.72

/call InternalMoveTo -1913.45 -1068.64

/call InternalMoveTo -1956.48 -981.83

/call InternalMoveTo -2032.72 -1022.45
/call InternalMoveTo -2086.45 -988.76

/call InternalMoveTo -2179.18 -1060.33

/call InternalMoveTo -2110.98 -1147.86

/call InternalMoveTo -2054.51 -1103.86

/call InternalMoveTo -1964.07 -1145.21
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1863.70 -1074.87
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1596.27 -1069.84
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1591.42 -1492.31
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1597.87 -1519.31

/call InternalMoveTo -1597.31 -1652.88

/call InternalMoveTo -1740.30 -1653.43
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1900.45 -1649.71
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1950.47 -1573.04

/call InternalMoveTo -1962.36 -1744.60

/call InternalMoveTo -2080.71 -1588.75

/call InternalMoveTo -2172.94 -1650.20
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2102.37 -1719.61
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo -2022.81,-1650.24
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return

sub valor 

/call InternalMoveTo  1.71 -261.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo  -646.00 -259.59
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo  -1045.20 -257.88
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo  -1048.76 -129.81
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo  -1026.39 -424.78
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1038.14 -509.62
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1078.99 -438.47
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1067.66 -247.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1439.19 -263.86
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1476.19 -203.25
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1490.11 -310.47
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1456.07 -259.45
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1631.76 -261.84
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1667.02 -76.34
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1657.41 -440.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1655.57 -387.62
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1790.27 -363.09
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1881.84 -451.40
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1885.80 -40.47
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1820.87 -151.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1812.02 -160.36
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1930.38 -251.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2223.83 -259.27
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2340.04 -76.43
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2325.35 -457.34
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2488.53 -125.51
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2643.25 -116.58
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2653.48 -65.68
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2699.16 -253.42
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2654.30 -456.03
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2500.96 -259.17
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2494.60 -862.75
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2651.35 -664.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2697.18 -851.70
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2652.34 -1035.05
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2587.99 -907.41
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2502.20 -865.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2492.86 -978.90
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2331.21 -978.72
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2332.15 -1057.32
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2330.92 -644.47
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -2337.22 -854.95
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1822.93 -858.36
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1996.17 -1017.16
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1812.28 -1058.22
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1615.26 -1019.54
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1784.04 -885.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1679.58 -893.44
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1677.79 -824.52
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1685.49 -699.14
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1616.62 -692.35
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1807.48 -664.87
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -1993.92 -692.31
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return


sub uwround

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call InternalMoveTo 1968.77 -115.69
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1969.71 261.67
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2030.05 296.16
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1914.69 292.43
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.65 281.38
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.74 437.64
/call KillAllMobs 10 30
/delay 1s
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2178.08 460.91
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1790.52 457.58
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1866.82 530.40
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1823.35 676.97
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1758.77 683.34
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2179.43 691.50
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2079.34 624.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1972.99 751.80
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1969.59 1036.95
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2159.81 1133.62
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1767.18 1131.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1985.80 1252.29
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2117.78 1296.58
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1981.52 1498.46
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 2164.77 1460.64
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1766.95 1455.96
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1954.57 1293.13
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1633.30 1296.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1387.08 1297.03
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1571.92 1447.60
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1395.16 1502.06
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1163.21 1457.54
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1185.99 1461.06
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1369.69 1322.57
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1240.32 1293.14
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1249.11 1296.05
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1294.30 1151.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1184.53 1128.99
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1583.11 1132.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1374.19 1134.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1374.17 645.77
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1525.69 800.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1570.46 623.78
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1530.41 418.48
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1414.16 614.88
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1376.59 481.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1182.99 619.12
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1203.80 801.29
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1212.10 441.26
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call InternalMoveTo 1360.03 630.43
/call InternalMoveTo 1372.25 782.29
/call InternalMoveTo 1376.62 1296.53
/call InternalMoveTo 1968.32 1298.56
/call InternalMoveTo 1970.80 711.87
/call InternalMoveTo 1872.46 662.37
/call InternalMoveTo 1872.46 485.02
/call InternalMoveTo 1969.00 488.57
/call InternalMoveTo 1963.77 -237.42
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45



/return
