sub heavens()
/moveto set dist 5
/moveto set loose on
/call RanInternalMoveTo -258.21 -2662.16
/call RanInternalMoveTo -9.49 -2665.18
/call RanInternalMoveTo -0.91 -2303.48
/call RanInternalMoveTo -382.29 -2315.37
/call RanInternalMoveTo -397.12 -1165.53
/call RanInternalMoveTo -398.71 -1039.90
/call RanInternalMoveTo -19.79 -1014.94
/call RanInternalMoveTo 836.03 -1023.63
/call RanInternalMoveTo 914.06 -1426.66
/call RanInternalMoveTo 879.31 -1539.13
/call RanInternalMoveTo 1026.88 -1417.88
/call RanInternalMoveTo 750.07 -1429.24
/call RanInternalMoveTo 861.32 -1510.36
/call RanInternalMoveTo 883.85 -1899.11
/call RanInternalMoveTo 1018.43 -1912.36
/call RanInternalMoveTo 739.15 -1922.10
/call RanInternalMoveTo 869.26 -2016.43
/call RanInternalMoveTo 887.99 -2304.86
/call RanInternalMoveTo 1535.55 -2317.69
/call RanInternalMoveTo 1672.12 -2317.63
/call RanInternalMoveTo 1730.22 -2279.82
/call RanInternalMoveTo 1720.79 -2376.82
/call RanInternalMoveTo 1727.66 -2334.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 400

/call RanInternalMoveTo 1684.71 -2320.91
/call KillAllMobs 10 30
/call LootIt 400

/return

sub hate

/call RanInternalMoveTo 1863.37 -2320.77
/call RanInternalMoveTo 1876.29 -2145.53
/call RanInternalMoveTo 1886.61 -2495.73
/call RanInternalMoveTo 1976.63 -2411.95
/call RanInternalMoveTo 2111.04 -2506.94
/call RanInternalMoveTo 2104.54 -2128.45
/call RanInternalMoveTo 2045.95 -2211.61
/call RanInternalMoveTo 2178.45 -2315.01
/call RanInternalMoveTo 2419.54 -2317.23
/call RanInternalMoveTo 2536.55 -2323.44
/call RanInternalMoveTo 2559.64 -2531.80
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call RanInternalMoveTo 2562.70 -2123.83
/call RanInternalMoveTo 2741.58 -2448.83
/call RanInternalMoveTo 2879.38 -2522.48
/call RanInternalMoveTo 2936.33 -2316.53
/call RanInternalMoveTo 2889.72 -2130.58
/call RanInternalMoveTo 2723.93 -2322.74
/call RanInternalMoveTo 2723.39 -1583.17
/call RanInternalMoveTo 2565.93 -1577.07
/call RanInternalMoveTo 2563.76 -1532.92
/call RanInternalMoveTo 2561.99 -1917.25
/call RanInternalMoveTo 2909.92 -1542.65
/call RanInternalMoveTo 2929.64 -1927.75
/call RanInternalMoveTo 2708.76 -1763.92
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call RanInternalMoveTo 2591.77 -1728.55
/call RanInternalMoveTo 2095.56 -1726.11
/call RanInternalMoveTo 1886.08 -1725.34
/call RanInternalMoveTo 1906.70 -1885.84
/call RanInternalMoveTo 1831.88 -1887.11
/call RanInternalMoveTo 2032.87 -1935.37
/call RanInternalMoveTo 2229.30 -1891.40
/call RanInternalMoveTo 2037.34 -1808.33
/call RanInternalMoveTo 1914.50 -1590.69
/call RanInternalMoveTo 1846.85 -1560.93
/call RanInternalMoveTo 2024.88 -1505.50
/call RanInternalMoveTo 2222.75 -1567.21
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/call RanInternalMoveTo 2024.88 -1505.50
/call RanInternalMoveTo 1846.85 -1560.93
/call RanInternalMoveTo 1914.50 -1590.69
/call RanInternalMoveTo 2037.34 -1808.33
/call RanInternalMoveTo 2229.30 -1891.40
/call RanInternalMoveTo 2032.87 -1935.37

/delay 2m

/return


sub xroad

/call RanInternalMoveTo -173.39 -2674.53


/call RanInternalMoveTo -6.42 -2664.50


/call RanInternalMoveTo -7.05 -2342.08


/call RanInternalMoveTo -360.79 -2317.46


/call RanInternalMoveTo -398.53 -2139.18


/call RanInternalMoveTo -396.12 -1141.09

/call RanInternalMoveTo -399.86 -1041.48

/call RanInternalMoveTo -217.89 -1017.65


/call RanInternalMoveTo -9.89 -1010.78


/call RanInternalMoveTo -1.63 -1010.54


/call RanInternalMoveTo 7.03 -995.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/return


sub abyss


/call RanInternalMoveTo 10.19 -923.69

/call RanInternalMoveTo 1.61 -745.94

/call RanInternalMoveTo 5.42 -416.30

/call RanInternalMoveTo 4.29 -381.89

/call RanInternalMoveTo 2.54 -130.29

/call RanInternalMoveTo -107.45 -254.26

/call RanInternalMoveTo 126.43 -257.44

/call RanInternalMoveTo 588.96 -258.06

/call RanInternalMoveTo 717.75 -262.25

/call RanInternalMoveTo 733.16 -407.27

/call RanInternalMoveTo 701.23 -554.96

/call RanInternalMoveTo 812.96 -553.43

/call RanInternalMoveTo 758.80 -486.21

/call RanInternalMoveTo 735.54 -105.85

/call RanInternalMoveTo 761.62 -43.58

/call RanInternalMoveTo 807.19 53.14

/call RanInternalMoveTo 736.41 61.64
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call RanInternalMoveTo 638.80 36.52

/call RanInternalMoveTo 713.03 -41.99

/call RanInternalMoveTo 782.78 -253.17

/call RanInternalMoveTo 1345.04 -260.94

/call RanInternalMoveTo 1783.24 -257.05

/call RanInternalMoveTo 1858.47 -261.72
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return

sub north

/call RanInternalMoveTo 2.20 -265.75


/call RanInternalMoveTo 736.02 -260.93


/call RanInternalMoveTo 1938.11 -259.02
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return


sub skies

/call RanInternalMoveTo 1964.83 -297.00

/call RanInternalMoveTo 1972.69 -529.38

/call RanInternalMoveTo 1972.17 -616.97
/call RanInternalMoveTo 1906.59 -730.64

/call RanInternalMoveTo 2019.44 -725.99

/call RanInternalMoveTo 1969.46 -747.37

/call RanInternalMoveTo 1969.88 -909.20

/call RanInternalMoveTo 1966.60 -1009.81

/call RanInternalMoveTo 1833.36 -1017.26

/call RanInternalMoveTo 1677.16 -1016.54

/call RanInternalMoveTo 1679.31 -1145.28

/call RanInternalMoveTo 1680.47 -1302.90

/call RanInternalMoveTo 1598.51 -1368.47

/call RanInternalMoveTo 1618.52 -1510.61

/call RanInternalMoveTo 1670.52 -1560.92

/call RanInternalMoveTo 1742.29 -1513.29

/call RanInternalMoveTo 1737.74 -1378.30

/call RanInternalMoveTo 1684.11 -1293.29

/call RanInternalMoveTo 1678.81 -1016.81

/call RanInternalMoveTo 2106.22 -1009.79

/call RanInternalMoveTo 2252.59 -1009.81

/call RanInternalMoveTo 2260.16 -1138.10

/call RanInternalMoveTo 2261.47 -1304.21

/call RanInternalMoveTo 2188.29 -1367.31

/call RanInternalMoveTo 2197.32 -1502.49


/call RanInternalMoveTo 2330.21 -1520.84

/call RanInternalMoveTo 2330.26 -1387.39
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/return

sub south

/call RanInternalMoveTo -496.21 -1020.17

/call RanInternalMoveTo -638.31 -1015.86

/call RanInternalMoveTo -998.10 -1020.88
/call RanInternalMoveTo -1127.03 -1058.92

/call RanInternalMoveTo -1130.56 -1356.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45



/return

sub uw

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call RanInternalMoveTo 1968.77 -115.69

/call RanInternalMoveTo 1969.71 261.67

/call RanInternalMoveTo 2030.05 296.16

/call RanInternalMoveTo 1914.69 292.43

/call RanInternalMoveTo 1972.65 281.38

/call RanInternalMoveTo 1972.74 437.64

/call RanInternalMoveTo 2178.08 460.91

/call RanInternalMoveTo 1790.52 457.58

/call RanInternalMoveTo 1866.82 530.40

/call RanInternalMoveTo 1823.35 676.97

/call RanInternalMoveTo 1758.77 683.34

/call RanInternalMoveTo 2179.43 691.50

/call RanInternalMoveTo 2079.34 624.15

/call RanInternalMoveTo 1972.99 751.80

/call RanInternalMoveTo 1969.59 1036.95

/call RanInternalMoveTo 2159.81 1133.62

/call RanInternalMoveTo 1767.18 1131.73

/call RanInternalMoveTo 1985.80 1252.29

/call RanInternalMoveTo 2117.78 1296.58
/call RanInternalMoveTo 1981.52 1498.46

/call RanInternalMoveTo 2164.77 1460.64

/call RanInternalMoveTo 1766.95 1455.96

/call RanInternalMoveTo 1954.57 1293.13

/call RanInternalMoveTo 1633.30 1296.10

/call RanInternalMoveTo 1387.08 1297.03

/call RanInternalMoveTo 1571.92 1447.60

/call RanInternalMoveTo 1395.16 1502.06

/call RanInternalMoveTo 1163.21 1457.54

/call RanInternalMoveTo 1185.99 1461.06

/call RanInternalMoveTo 1369.69 1322.57

/call RanInternalMoveTo 1240.32 1293.14

/call RanInternalMoveTo 1249.11 1296.05

/call RanInternalMoveTo 1294.30 1151.15

/call RanInternalMoveTo 1184.53 1128.99

/call RanInternalMoveTo 1583.11 1132.18

/call RanInternalMoveTo 1374.19 1134.37

/call RanInternalMoveTo 1374.17 645.77

/call RanInternalMoveTo 1525.69 800.04

/call RanInternalMoveTo 1570.46 623.78

/call RanInternalMoveTo 1530.41 418.48

/call RanInternalMoveTo 1414.16 614.88

/call RanInternalMoveTo 1376.59 481.10

/call RanInternalMoveTo 1182.99 619.12

/call RanInternalMoveTo 1203.80 801.29

/call RanInternalMoveTo 1212.10 441.26
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return

sub storms

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call RanInternalMoveTo -1368.18 -1362.18

/call RanInternalMoveTo -1457.96 -1362.26

/call RanInternalMoveTo -1581.69 -1358.39
/call RanInternalMoveTo -1598.42 -1224.01

/call RanInternalMoveTo -1596.56 -1070.87

/call RanInternalMoveTo -1736.84 -1068.72

/call RanInternalMoveTo -1913.45 -1068.64

/call RanInternalMoveTo -1956.48 -981.83

/call RanInternalMoveTo -2032.72 -1022.45
/call RanInternalMoveTo -2086.45 -988.76

/call RanInternalMoveTo -2179.18 -1060.33

/call RanInternalMoveTo -2110.98 -1147.86

/call RanInternalMoveTo -2054.51 -1103.86

/call RanInternalMoveTo -1964.07 -1145.21

/call RanInternalMoveTo -1863.70 -1074.87

/call RanInternalMoveTo -1596.27 -1069.84

/call RanInternalMoveTo -1591.42 -1492.31

/call RanInternalMoveTo -1597.87 -1519.31

/call RanInternalMoveTo -1597.31 -1652.88

/call RanInternalMoveTo -1740.30 -1653.43

/call RanInternalMoveTo -1900.45 -1649.71

/call RanInternalMoveTo -1950.47 -1573.04

/call RanInternalMoveTo -1962.36 -1744.60

/call RanInternalMoveTo -2080.71 -1588.75

/call RanInternalMoveTo -2172.94 -1650.20

/call RanInternalMoveTo -2102.37 -1719.61

/call RanInternalMoveTo -2022.81 -1650.24
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return

sub valor 

/call RanInternalMoveTo  1.71 -261.37

/call RanInternalMoveTo  -646.00 -259.59

/call RanInternalMoveTo  -1045.20 -257.88

/call RanInternalMoveTo  -1048.76 -129.81

/call RanInternalMoveTo  -1026.39 -424.78

/call RanInternalMoveTo -1038.14 -509.62

/call RanInternalMoveTo -1078.99 -438.47

/call RanInternalMoveTo -1067.66 -247.73

/call RanInternalMoveTo -1439.19 -263.86

/call RanInternalMoveTo -1476.19 -203.25

/call RanInternalMoveTo -1490.11 -310.47

/call RanInternalMoveTo -1456.07 -259.45

/call RanInternalMoveTo -1631.76 -261.84

/call RanInternalMoveTo -1667.02 -76.34

/call RanInternalMoveTo -1657.41 -440.37

/call RanInternalMoveTo -1655.57 -387.62

/call RanInternalMoveTo -1790.27 -363.09

/call RanInternalMoveTo -1881.84 -451.40

/call RanInternalMoveTo -1885.80 -40.47

/call RanInternalMoveTo -1820.87 -151.15

/call RanInternalMoveTo -1812.02 -160.36

/call RanInternalMoveTo -1930.38 -251.18

/call RanInternalMoveTo -2223.83 -259.27

/call RanInternalMoveTo -2340.04 -76.43

/call RanInternalMoveTo -2325.35 -457.34

/call RanInternalMoveTo -2488.53 -125.51

/call RanInternalMoveTo -2643.25 -116.58

/call RanInternalMoveTo -2653.48 -65.68

/call RanInternalMoveTo -2699.16 -253.42

/call RanInternalMoveTo -2654.30 -456.03

/call RanInternalMoveTo -2500.96 -259.17

/call RanInternalMoveTo -2494.60 -862.75

/call RanInternalMoveTo -2651.35 -664.04

/call RanInternalMoveTo -2697.18 -851.70

/call RanInternalMoveTo -2652.34 -1035.05

/call RanInternalMoveTo -2587.99 -907.41

/call RanInternalMoveTo -2502.20 -865.37

/call RanInternalMoveTo -2492.86 -978.90

/call RanInternalMoveTo -2331.21 -978.72

/call RanInternalMoveTo -2332.15 -1057.32

/call RanInternalMoveTo -2330.92 -644.47

/call RanInternalMoveTo -2337.22 -854.95

/call RanInternalMoveTo -1822.93 -858.36

/call RanInternalMoveTo -1996.17 -1017.16

/call RanInternalMoveTo -1812.28 -1058.22

/call RanInternalMoveTo -1615.26 -1019.54

/call RanInternalMoveTo -1784.04 -885.18

/call RanInternalMoveTo -1679.58 -893.44

/call RanInternalMoveTo -1677.79 -824.52

/call RanInternalMoveTo -1685.49 -699.14

/call RanInternalMoveTo -1616.62 -692.35

/call RanInternalMoveTo -1807.48 -664.87

/call RanInternalMoveTo -1993.92 -692.31
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45


/return


sub uwround

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call RanInternalMoveTo 1968.77 -115.69
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1969.71 261.67
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2030.05 296.16
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1914.69 292.43
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1972.65 281.38
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1972.74 437.64
/call KillAllMobs 10 30
/delay 1s
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2178.08 460.91
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1790.52 457.58
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1866.82 530.40
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1823.35 676.97
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1758.77 683.34
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2179.43 691.50
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2079.34 624.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1972.99 751.80
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1969.59 1036.95
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2159.81 1133.62
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1767.18 1131.73
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1985.80 1252.29
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2117.78 1296.58
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1981.52 1498.46
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 2164.77 1460.64
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1766.95 1455.96
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1954.57 1293.13
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1633.30 1296.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1387.08 1297.03
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1571.92 1447.60
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1395.16 1502.06
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1163.21 1457.54
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1185.99 1461.06
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1369.69 1322.57
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1240.32 1293.14
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1249.11 1296.05
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1294.30 1151.15
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1184.53 1128.99
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1583.11 1132.18
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1374.19 1134.37
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1374.17 645.77
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1525.69 800.04
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1570.46 623.78
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1530.41 418.48
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1414.16 614.88
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1376.59 481.10
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1182.99 619.12
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1203.80 801.29
/call KillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call KillAllMobs 10 30
/call LootIt 45
/call RanInternalMoveTo 1212.10 441.26
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45

/call RanInternalMoveTo 1360.03 630.43
/call RanInternalMoveTo 1372.25 782.29
/call RanInternalMoveTo 1376.62 1296.53
/call RanInternalMoveTo 1968.32 1298.56
/call RanInternalMoveTo 1970.80 711.87
/call RanInternalMoveTo 1872.46 662.37
/call RanInternalMoveTo 1872.46 485.02
/call RanInternalMoveTo 1969.00 488.57
/call RanInternalMoveTo 1963.77 -237.42
/call KillAllMobs 10 30
/delay 1s
/call KillAllMobs 10 30
/call LootIt 45



/return
