     |** LDON5 **|
sub ldon5
/echo Starting LDON5 Run
:L51
/call InternalMoveTo -837 45
/call InternalMoveTo -838 -1
/call InternalMoveTo -836 -68
/call KillAllMobs 10 35
/call LootIt 45
/echo at loc -836 -68
/call InternalMoveTo -827 -111
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -892 -124
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -834 -108
/call InternalMoveTo -777 -85
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -775 -113
/call InternalMoveTo -770 -156
/call KillAllMobs 10 35
/call LootIt 45
/echo at loc -770 -156
/call InternalMoveTo -741 -150
/call InternalMoveTo -700 -149
/call InternalMoveTo -641 -149
/echo at loc -641 -149
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -639 -184
/call InternalMoveTo -622 -186
/call InternalMoveTo -600 -187
/echo at loc -600 -187
/call KillAllMobs 10 27
/call LootIt 45
/call InternalMoveTo -584 -187
/call InternalMoveTo -581 -211
/call InternalMoveTo -554 -214
/call InternalMoveTo -546 -212
/echo at loc -546 -212
/delay 15
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -549 -240
/call InternalMoveTo -537 -245
/call InternalMoveTo -472 -250
/echo at loc -472  -250
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -479 -237
/call InternalMoveTo -499 -210
/call InternalMoveTo -517 -187
/echo at loc -517 -187
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -517 -185
/call InternalMoveTo -487 -185
/call InternalMoveTo -485 -145
/echo at loc -485 -145
/call InternalMoveTo -489 -113
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -487 -84
/call InternalMoveTo -524 -31
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -563 -44
/call InternalMoveTo -605 -56
/call InternalMoveTo -635 -44
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -596 -50
/call InternalMoveTo -528 -48
/call InternalMoveTo -484 -47
/call InternalMoveTo -488 2
/call InternalMoveTo -489 41
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -489 -3
/call InternalMoveTo -483 -41
/call InternalMoveTo -425 -40
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -410 -42
/call InternalMoveTo -374 -44
/call InternalMoveTo -349 -45
/call InternalMoveTo -351 -31
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -343 -19
/call InternalMoveTo -322 -19
/call InternalMoveTo -325 -1
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -314 -15
/call InternalMoveTo -303 -20
/call InternalMoveTo -245 -25
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -238 -1
/call InternalMoveTo -213 1
/call InternalMoveTo -212 30
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -208 31
/call InternalMoveTo -174 29
/call InternalMoveTo -125 28
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -90 28
/call InternalMoveTo -63 28
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -24 64
/call InternalMoveTo -28 79
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 12 81
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 25 66
/call InternalMoveTo 66 18
/call KillAllMobs 10 35
/call LootIt 45
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -2 40
/call InternalMoveTo 0 12
/call InternalMoveTo 1 -30
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -6 -39
/call InternalMoveTo -28 -42
/call InternalMoveTo -29 -64
/call InternalMoveTo -39 -65
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 3 -72
/call InternalMoveTo 67 -75
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 32 -78
/call InternalMoveTo 12 -86
/call InternalMoveTo 23 -115
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 41 -137
/call InternalMoveTo 53 -162
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 40 -137
/call InternalMoveTo 38 -116
/call InternalMoveTo 68 -116
/call InternalMoveTo 99 -116
/call InternalMoveTo 162 -117
/call InternalMoveTo 189 -118
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 232 -126
/call InternalMoveTo 265 -166
/call InternalMoveTo 297 -186
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 315 -180
/call InternalMoveTo 353 -177
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 364 -179
/call InternalMoveTo 365 -201
/call InternalMoveTo 401 -214
/call InternalMoveTo 390 -230
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 405 -182
/call InternalMoveTo 413 -155
/call InternalMoveTo 448 -159
/call InternalMoveTo 444 -126
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 459 -136
/call InternalMoveTo 495 -136
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 454 -137
/call InternalMoveTo 439 -107
/call InternalMoveTo 441 -66
/call InternalMoveTo 440 -14
/call InternalMoveTo 441 21
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 441 27
/call InternalMoveTo 416 26
/call InternalMoveTo 423 75
/call InternalMoveTo 430 124
/call InternalMoveTo 445 122
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 451 121
/call InternalMoveTo 452 92
/call InternalMoveTo 485 94
/call InternalMoveTo 531 97
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 524 121
/call InternalMoveTo 525 199
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 526 151
/call InternalMoveTo 526 139
/call InternalMoveTo 594 144
/call InternalMoveTo 641 146
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 649 124
/call InternalMoveTo 653 105
/call InternalMoveTo 672 105
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 677 105
/call InternalMoveTo 676 75
/call InternalMoveTo 675 49
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 692 -7
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 692 10
/call InternalMoveTo 729 9
/call InternalMoveTo 777 9
/call InternalMoveTo 818 9
/call KillAllMobs 10 28
/call LootIt 45
/call InternalMoveTo 820 39
/call InternalMoveTo 852 38
/call InternalMoveTo 854 7
/call KillAllMobs 10 28
/call LootIt 45
/call InternalMoveTo 880 6
/call InternalMoveTo 879 -18
/call InternalMoveTo 909 -15
/call InternalMoveTo 904 -63
/call InternalMoveTo 906 -148
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 905 -92
/call InternalMoveTo 903 -49
/call InternalMoveTo 903 -11
/call InternalMoveTo 873 -12
/call InternalMoveTo 875 32
/call InternalMoveTo 914 33
/call InternalMoveTo 957 33
/call InternalMoveTo 1000 34
/call KillAllMobs 10 43
/call LootIt 45
/call InternalMoveTo 1011 16
/call InternalMoveTo 1048 13
/call InternalMoveTo 1047 -19
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 1042 57
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 1098 75
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 1093 9
/call InternalMoveTo 1126 -25
/call KillAllMobs 10 34
/call LootIt 45
/call InternalMoveTo 1118 -12
/call InternalMoveTo 1153 -13
/call InternalMoveTo 1214 -13
/call InternalMoveTo 1267 -13
/call InternalMoveTo 1275 -13
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo 1204 -12
/call InternalMoveTo 1127 -11
/call InternalMoveTo 1045 14
/call InternalMoveTo 998 20
/call InternalMoveTo 980 36
/call InternalMoveTo 922 32
/call InternalMoveTo 882 32
/call InternalMoveTo 861 94
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 888 69
/call InternalMoveTo 837 34
/call InternalMoveTo 815 31
/call InternalMoveTo 816 1
/call InternalMoveTo 782 7
/call InternalMoveTo 694 8
/call InternalMoveTo 673 48
/call InternalMoveTo 678 112
/call InternalMoveTo 649 107
/call InternalMoveTo 647 150
/call InternalMoveTo 601 144
/call InternalMoveTo 524 143
/call InternalMoveTo 523 96
/call InternalMoveTo 454 94
/call InternalMoveTo 446 123
/call InternalMoveTo 429 126
/call InternalMoveTo 425 159
/call InternalMoveTo 403 201
/delay 2s
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 403 198
/call InternalMoveTo 374 199
/call InternalMoveTo 380 271
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 379 309
/call InternalMoveTo 379 351
/call InternalMoveTo 393 359
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 434 358
/call InternalMoveTo 476 359
/call InternalMoveTo 487 360
/call InternalMoveTo 487 378
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 488 413
/call InternalMoveTo 491 456
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 457 470
/call InternalMoveTo 404 474
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 454 475
/call InternalMoveTo 488 454
/call InternalMoveTo 490 407
/call InternalMoveTo 490 363
/call InternalMoveTo 469 358
/call InternalMoveTo 430 359
/call InternalMoveTo 386 357
/call InternalMoveTo 375 345
/call InternalMoveTo 379 304
/call InternalMoveTo 380 258
/call InternalMoveTo 379 198
/call InternalMoveTo 382 198
/call InternalMoveTo 408 198
/call InternalMoveTo 405 184
/call InternalMoveTo 386 157
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 382 150
/call InternalMoveTo 375 123
/call InternalMoveTo 381 113
/call InternalMoveTo 405 99
/call InternalMoveTo 420 64
/call InternalMoveTo 417 23
/call InternalMoveTo 414 35
/call InternalMoveTo 442 16
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 446 17
/call InternalMoveTo 444 -48
/call InternalMoveTo 443 -107
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 442 -136
/call InternalMoveTo 497 -134
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 465 -138
/call InternalMoveTo 450 -141
/call InternalMoveTo 425 -158
/call InternalMoveTo 397 -162
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 398 -190
/call InternalMoveTo 394 -216
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 380 -206
/call InternalMoveTo 357 -203
/call InternalMoveTo 362 -179
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 362 -177
/call InternalMoveTo 301 -180
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 268 -173
/call InternalMoveTo 236 -131
/call InternalMoveTo 198 -119
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 166 -118
/call InternalMoveTo 106 -118
/call InternalMoveTo 61 -118
/call InternalMoveTo 44 -121
/call KillAllMobs 10 44
/call LootIt 45
/call InternalMoveTo 42 -121
/call InternalMoveTo 45 -167
/call InternalMoveTo 7 -180
/call InternalMoveTo 7 -189
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 13 -168
/call InternalMoveTo 42 -151
/call InternalMoveTo 44 -128
/call InternalMoveTo 19 -108
/call InternalMoveTo 17 -72
/call InternalMoveTo 46 -77
/call InternalMoveTo 66 -75
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 38 -76
/call InternalMoveTo 2 -75
/call InternalMoveTo -44 -70
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -29 -62
/call InternalMoveTo -26 -37
/call InternalMoveTo -2 -39
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -1 -6
/call InternalMoveTo 0 41
/call InternalMoveTo 56 32
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 9 76
/call InternalMoveTo 18 92
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo 6 66
/call InternalMoveTo -30 95
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -16 64
/call InternalMoveTo -59 33
/call KillAllMobs 10 40
/call LootIt 45
/call InternalMoveTo -86 28
/call InternalMoveTo -125 26
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -177 27
/call InternalMoveTo -214 28
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -208 24
/call InternalMoveTo -213 1
/call InternalMoveTo -228 0
/call InternalMoveTo -244 -22
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -252 -26
/call InternalMoveTo -310 -20
/call InternalMoveTo -325 14
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -330 -19
/call InternalMoveTo -355 -23
/call InternalMoveTo -349 -50
/call InternalMoveTo -406 -47
/call InternalMoveTo -421 -45
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -457 -48
/call InternalMoveTo -524 -22
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -509 -60
/call InternalMoveTo -487 -105
/call InternalMoveTo -487 -115
/call KillAllMobs 10 30
/call LootIt 45
/call InternalMoveTo -479 -192
/call InternalMoveTo -514 -186
/call InternalMoveTo -516 -187
/call InternalMoveTo -516 -197
/call InternalMoveTo -518 -213
/call InternalMoveTo -525 -225
/call InternalMoveTo -546 -223
/call InternalMoveTo -566 -213
/call InternalMoveTo -582 -214
/call InternalMoveTo -588 -187
/call InternalMoveTo -586 -183
/call InternalMoveTo -615 -186
/call InternalMoveTo -644 -186
/call InternalMoveTo -641 -148
/call InternalMoveTo -650 -149
/call InternalMoveTo -697 -150
/call InternalMoveTo -756 -149
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -774 -129
/call InternalMoveTo -779 -81
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -781 -103
/call InternalMoveTo -834 -67
/call KillAllMobs 10 35
/call LootIt 45
/call InternalMoveTo -839 -67
/call InternalMoveTo -838 -6
/call InternalMoveTo -839 74
/call InternalMoveTo -839 71
/goto :L51
/return