sub fear

/call InternalMoveTo -1138.04 1096.89
/call cycle
/call InternalMoveTo -1064.49 995.13
/call cycle
/call InternalMoveTo -1310.42 645.87
/call cycle
/call InternalMoveTo -1123.97 540.32
/call cycle
/call InternalMoveTo -1233.90 316.66
/call cycle
/call InternalMoveTo -1214.75 254.01
/call cycle
/call InternalMoveTo -1186.26 119.50
/call cycle
/call InternalMoveTo -1318.78 -179.54
/call cycle
/call InternalMoveTo -1257.49 -487.54
/call cycle
/call InternalMoveTo -1166.76 -619.75
/call cycle
/call InternalMoveTo -1031.29 -751.91
/call cycle
/call InternalMoveTo -1302.07 -826.31
/call cycle
/call InternalMoveTo -1312.18 -1032.50
/call cycle
/call InternalMoveTo -1154.21 -1319.42
/call cycle
/call InternalMoveTo -794.16 -1414.27
/call cycle
/call InternalMoveTo -786.84 -1143.54
/call cycle
/call InternalMoveTo -373.63 -978.27
/call cycle
/call InternalMoveTo -355.34 -1051.29
/call cycle
/call InternalMoveTo 26.90 -789.03
/call cycle
/call KillFace 60
/delay 5s
/call KillFace 60
/call InternalMoveTo 282.49 -435.40
/call InternalMoveTo 905.75 -660.44
/call cycle
/call InternalMoveTo 1355.91 -206.65
/call cycle
/call InternalMoveTo 1311.01 -574.83
/call cycle
/call InternalMoveTo 1137.11 -809.25
/call cycle
/call InternalMoveTo 1172.99 -1207.95
/call cycle
/call InternalMoveTo 641.87 -880.68
/call cycle
/call InternalMoveTo 130.81 -912.05
/call cycle
/call InternalMoveTo -210.59 -1068.40
/call cycle
/call InternalMoveTo -694.10 -908.65
/call cycle
/call InternalMoveTo -964.09 -780.93
/call cycle
/call InternalMoveTo -1091.32 -542.86
/call cycle
/call InternalMoveTo -1038.27 -258.03
/call cycle
/call InternalMoveTo -727.21 -81.82
/call cycle
/call InternalMoveTo -360.50 -56.73
/call cycle
/call InternalMoveTo -446.46 226.66
/call cycle
/call InternalMoveTo -695.85 554.45
/call cycle
/call InternalMoveTo -532.49 774.69
/call cycle
/call KillFace 60
/delay 5s
/call KillFace 60
/call InternalMoveTo -159.79 1168.15
/call cycle
/call InternalMoveTo -41.02 1201.01
/call cycle
/call InternalMoveTo -479.26 1004.37
/call cycle
/call InternalMoveTo -679.94 443.39
/call cycle
/call InternalMoveTo -940.99 572.01
/call cycle
/call InternalMoveTo -1040.21 477.53
/call cycle
/call InternalMoveTo -1097.26 537.75
/call cycle
/delay 5s
/call KillFace 60
/delay 5s
/call KillFace 60



/call loot 60 70 80

/return 
