sub hate

|takes a parm indicating who to loot

|/goto :block5

|Divide into Heavens and Hate

:block1

/call HoHInternalMoveTo -254.23 -2674.64


/call HoHInternalMoveTo -2.75 -2674.36
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s

/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -0.47 -2478.54
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -0.76 -2101.75
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 3.25 -2327.75
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 394.96 -2321.54
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}
/call HoHInternalMoveTo 410.96 -2283.42
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/keypress 0

/call HoHInternalMoveTo 385.05 -1926.50
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

:block2


/call HoHInternalMoveTo 218.96 -1923.22
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/delay 5s
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 382.35 -1920.33
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 400.35 -1721.21
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 402.84 -1499.77
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call HoHInternalMoveTo -11.55 -1537.31
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -3.02 -1632.34
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -7.85 -1543.42
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/keypress 0

/call HoHInternalMoveTo -175.13 -1515.73
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -390.18 -1515.65
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -396.90 -1760.30
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -390.87 -1915.19
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -281.49 -1918.57
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}


:block3

/call HoHInternalMoveTo -377.27 -1918.38
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/keypress 0

/call HoHInternalMoveTo -397.14 -2105.31
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo -389.74 -2325.82
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 382.97 -2319.32
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 387.62 -1972.55
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 390.59 -1855.15
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/keypress 0

/call HoHInternalMoveTo 395.08 -1180.99
/call HoHKillAllMobs 10 60
/keypress 0
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHInternalMoveTo 397.98 -1062.72
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/call HoHInternalMoveTo 448.69 -1017.22
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) {

/call wait

}

/keypress 0

/call HoHInternalMoveTo 803.45 -1016.54
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 806.80 -1027.49
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 881.24 -1097.76
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 876.76 -1412.53
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/keypress 0

/call HoHInternalMoveTo 734.93 -1400.25
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 729.58 -1450.34
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1024.39 -1450.56
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1041.09 -1407.96
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


:block4


/call HoHInternalMoveTo 888.67 -1428.36
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo 881.34 -1925.46
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 741.48 -1906.68
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 740.01 -1948.55
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1018.57 -1953.23
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1023.24 -1928.49
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 879.81 -1924.83
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 883.74 -2286.91
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 993.56 -2322.13
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 996.58 -2326.70
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1356.86 -2321.36
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1684.76 -2319.82
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1735.97 -2276.07
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1733.47 -2377.84
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1719.10 -2336.21
/call HoHKillAllMobs 10 60
/delay 1s
/call HoHKillAllMobs 10 60
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

|Hate Ent|
/call HoHInternalMoveTo 1702.38 -2320.35
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1875.99 -2321.20
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1886.48 -2518.12
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1942.45 -2429.83
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2074.62 -2424.94
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2103.58 -2546.22
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2109.40 -2345.00
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2200.59 -2317.81
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2116.90 -2247.43
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2102.88 -2114.08
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2032.69 -2208.85
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2152.21 -2320.77
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

:block5
/call HoHInternalMoveTo 2626.10 -2330.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2565.33 -2530.80
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2669.33 -2364.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2720.74 -2472.46
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2800.92 -2362.06
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2890.19 -2534.97
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2886.05 -2107.65
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2722.10 -2377.71
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2725.00 -1783.72
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2721.43 -1759.09
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2892.04 -1914.89
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2925.57 -1726.66
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2891.63 -1533.11
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2739.86 -1725.87
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2720.51 -1583.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2551.74 -1591.55
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2559.76 -1510.21
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2619.99 -1725.08
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2077.93 -1729.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2177.18 -1565.64
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2254.35 -1547.30
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2056.35 -1512.03
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1844.68 -1559.80
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2022.90 -1714.57
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 1855.13 -1883.26
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2040.89 -1923.66
/call HoHKillAllMobs 10 20
/delay 1s
/call HoHKillAllMobs 10 20
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }
/call HoHInternalMoveTo 2225.74 -1891.87
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot

/call HoHInternalMoveTo 2040.89 -1923.66

/delay 3s
/call HoHKillAllMobs 10 35
/delay 1s
/call HoHKillAllMobs 10 35
/bct ${Param0} //macro hohloot
/delay 40s

/return




sub xroad

/call HoHInternalMoveTo -173.39 -2674.53
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -6.42 -2664.50
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -7.05 -2342.08
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -360.79 -2317.46
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot

/call HoHInternalMoveTo -398.53 -2139.18
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -396.12 -1141.09
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call HoHInternalMoveTo -399.86 -1041.48
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -217.89 -1017.65
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -9.89 -1010.78
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -1.63 -1010.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }



/call HoHInternalMoveTo 7.03 -995.04
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/return


sub abyss


/call HoHInternalMoveTo 10.19 -923.69
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1.61 -745.94
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 5.42 -416.30
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 4.29 -381.89
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2.54 -130.29
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -107.45 -254.26
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 126.43 -257.44
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 588.96 -258.06
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 717.75 -262.25
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 733.16 -407.27
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 701.23 -554.96
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 812.96 -553.43
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 758.80 -486.21
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 735.54 -105.85
/call HoHKillAllMobs 10 30
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 761.62 -43.58
/call HoHKillAllMobs 10 30
/delay 1s

/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 807.19 53.14
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 736.41 61.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 638.80 36.52
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 713.03 -41.99
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 782.78 -253.17
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1345.04 -260.94
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1783.24 -257.05
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1858.47 -261.72
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/return

sub north

/call HoHInternalMoveTo 2.20 -265.75
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo 736.02 -260.93
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo 1938.11 -259.02
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot


/return


sub skies

/call HoHInternalMoveTo 1964.83 -297.00
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1972.69 -529.38
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1972.17 -616.97
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1906.59 -730.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2019.44 -725.99
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1969.46 -747.37
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1969.88 -909.20
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1966.60 -1009.81
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1833.36 -1017.26
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1677.16 -1016.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1679.31 -1145.28
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1680.47 -1302.90
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1598.51 -1368.47
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1618.52 -1510.61
/call HoHKillAllMobs 10 30

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1670.52 -1560.92
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1742.29 -1513.29
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1737.74 -1378.30
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1684.11 -1293.29
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1678.81 -1016.81
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2106.22 -1009.79
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2252.59 -1009.81
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2260.16 -1138.10
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2261.47 -1304.21
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2188.29 -1367.31
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2197.32 -1502.49
/call HoHKillAllMobs 10 30
/delay 1sA
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo 2330.21 -1520.84
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2330.26 -1387.39
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/return

sub south

/call HoHInternalMoveTo -496.21 -1020.17
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -638.31 -1015.86
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/call HoHInternalMoveTo -998.10 -1020.88
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1127.03 -1058.92
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1130.56 -1356.73
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }




/return

sub uw

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call HoHInternalMoveTo 1968.77 -115.69
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1969.71 261.67
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2030.05 296.16
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1914.69 292.43
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1972.65 281.38
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1972.74 437.64
/call HoHKillAllMobs 10 30
/delay 1s
/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2178.08 460.91
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1790.52 457.58
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1866.82 530.40
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1823.35 676.97
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1758.77 683.34
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2179.43 691.50
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2079.34 624.15
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1972.99 751.80
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1969.59 1036.95
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2159.81 1133.62
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1767.18 1131.73
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1985.80 1252.29
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2117.78 1296.58
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1981.52 1498.46
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 2164.77 1460.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1766.95 1455.96
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1954.57 1293.13
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1633.30 1296.10
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1387.08 1297.03
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1571.92 1447.60
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1395.16 1502.06
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1163.21 1457.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1185.99 1461.06
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1369.69 1322.57
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1240.32 1293.14
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1249.11 1296.05
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1294.30 1151.15
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1184.53 1128.99
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1583.11 1132.18
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1374.19 1134.37
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1374.17 645.77
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1525.69 800.04
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1570.46 623.78
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1530.41 418.48
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1414.16 614.88
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1376.59 481.10
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1182.99 619.12
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1203.80 801.29
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo 1212.10 441.26
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }



/return

sub storms

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}

/call HoHInternalMoveTo -1368.18 -1362.18
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1457.96 -1362.26
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1581.69 -1358.39
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1598.42 -1224.01
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1596.56 -1070.87
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1736.84 -1068.72
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1913.45 -1068.64
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1956.48 -981.83
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2032.72 -1022.45
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2086.45 -988.76
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2179.18 -1060.33
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2110.98 -1147.86
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2054.51 -1103.86
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1964.07 -1145.21
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1863.70 -1074.87
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1596.27 -1069.84
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1591.42 -1492.31
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1597.87 -1519.31
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1597.31 -1652.88
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1740.30 -1653.43
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1900.45 -1649.71
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1950.47 -1573.04
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1962.36 -1744.60
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2080.71 -1588.75
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2172.94 -1650.20
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2102.37 -1719.61
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }


/call HoHInternalMoveTo -2022.81,-1650.24
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }



/return

sub valor 

/call HoHInternalMoveTo  1.71 -261.37
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo  -646.00 -259.59
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo  -1045.20 -257.88
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo  -1048.76 -129.81
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo  -1026.39 -424.78
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1038.14 -509.62
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1078.99 -438.47
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1067.66 -247.73
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1439.19 -263.86
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1476.19 -203.25
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1490.11 -310.47
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1456.07 -259.45
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1631.76 -261.84
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1667.02 -76.34
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1657.41 -440.37
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1655.57 -387.62
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1790.27 -363.09
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1881.84 -451.40
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1885.80 -40.47
/call HoHKillAllMobs 10 30
/delay 1s

/if (!${Zone.Name.Equal[The Halls of Honor]}) {
/camp
/delay 40s
/endmacro
}
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1820.87 -151.15
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1812.02 -160.36
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1930.38 -251.18
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2223.83 -259.27
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2340.04 -76.43
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2325.35 -457.34
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2488.53 -125.51
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2643.25 -116.58
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2653.48 -65.68
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2699.16 -253.42
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2654.30 -456.03
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2500.96 -259.17
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2494.60 -862.75
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2651.35 -664.04
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2697.18 -851.70
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2652.34 -1035.05
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2587.99 -907.41
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2502.20 -865.37
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2492.86 -978.90
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2331.21 -978.72
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2332.15 -1057.32
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2330.92 -644.47
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -2337.22 -854.95
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1822.93 -858.36
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1996.17 -1017.16
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1812.28 -1058.22
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1615.26 -1019.54
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1784.04 -885.18
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1679.58 -893.44
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1677.79 -824.52
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1685.49 -699.14
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1616.62 -692.35
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1807.48 -664.87
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }

/call HoHInternalMoveTo -1993.92 -692.31
/call HoHKillAllMobs 10 30
/delay 1s
/call HoHKillAllMobs 10 30
/bct ${Param0} //macro hohloot
/if (${SpawnCount[CORPSE radius 60]}) { /call wait }



/return

sub wait

/delay 2s

/return


